// The project's ONE reader-facing number formatter, tested directly rather
// than only through rendered output.
//
// THE DEFECT THIS DRIVES. Every reader-facing numeral on this site was
// produced by `Number.prototype.toFixed`, which is locale-blind by
// specification: it always emits a `.` decimal point and never a grouping
// separator. The homepage therefore shipped `49687120 personas` and
// `22779 miles de personas` — figures a Spanish reader has to count digits
// on to interpret, on a site whose entire `lang` is `es`.
//
// WHY A DIRECT UNIT TEST AND NOT ONLY A PAGE ASSERTION. The rendered-output
// tests can only check the handful of magnitudes the fixture happens to
// contain. The behaviour that actually matters here is the RULE — Spanish
// grouping is not "insert a dot every three digits", it is CLDR's
// `minimumGroupingDigits: 2`, which leaves a four-digit number ungrouped
// (`1234`, never `1.234`; RAE, *Ortografía* §11.5.1.2). No fixture series
// has a four-digit latest value, so no page assertion can prove or disprove
// that rule. This file constructs the magnitudes on purpose.
import { describe, expect, it } from "vitest";

import { formatNumber, formatSignedPercent } from "../../src/lib/format/number";

describe("formatNumber — Spanish reader-facing numerals", () => {
  it("groups thousands with a point, the way a Spanish reader reads them", () => {
    // The two figures that were live on the homepage unformatted.
    expect(formatNumber(22779, 0)).toBe("22.779");
    expect(formatNumber(49687120, 0)).toBe("49.687.120");
  });

  it("uses a comma as the decimal separator, never a point", () => {
    expect(formatNumber(9.87, 2)).toBe("9,87");
    expect(formatNumber(103.598, 2)).toBe("103,60");
  });

  it("honours the per-series decimal count exactly, padding and rounding to it", () => {
    // PIB is configured to four decimals deliberately, and 121.9959 is a
    // real published figure — a formatter that quietly normalised every
    // series to two would erase three significant digits of it.
    expect(formatNumber(121.9959, 4)).toBe("121,9959");
    // Padding matters as much as rounding: a column of values that showed
    // "22.779" beside "22.779,4" would misalign and misreport precision.
    expect(formatNumber(22779, 1)).toBe("22.779,0");
    expect(formatNumber(0, 2)).toBe("0,00");
  });

  it("leaves a FOUR-digit number ungrouped, which is the Spanish rule and not an oversight", () => {
    // `1.234` is the English-speaker's instinct and it is wrong here: in
    // Spanish typography the separator appears from five digits up. Pinning
    // it means a future switch to a hand-rolled "every three digits" loop,
    // or to `useGrouping: "always"`, goes red instead of shipping.
    expect(formatNumber(1234, 0)).toBe("1234");
    expect(formatNumber(1234, 2)).toBe("1234,00");
    expect(formatNumber(999, 0)).toBe("999");
    expect(formatNumber(10000, 0)).toBe("10.000");
  });

  it("emits only ASCII separators, so no non-breaking space reaches the markup", () => {
    // Several locales' `Intl` output carries U+00A0, and some `style`
    // options insert one unconditionally. One arriving here would be
    // invisible in a diff and would break every `toContain("22.779")`
    // assertion downstream for a reason nobody could see.
    for (const rendered of [formatNumber(49687120, 0), formatNumber(121.9959, 4), formatNumber(-3.4, 1)]) {
      expect(rendered, `"${rendered}" carries a non-ASCII character`).toMatch(/^[-0-9.,]+$/);
    }
  });

  it("rounds an exact decimal half AWAY FROM ZERO, which `toFixed` did not", () => {
    // A real behavioural difference this change introduces, pinned rather
    // than discovered later. `(70.865).toFixed(2)` is "70.86", because the
    // double nearest 70.865 is 70.86499999999999488…, and `toFixed` rounds
    // that binary value. `Intl` rounds the DECIMAL the artifact actually
    // published, so it returns 70,87 — the answer a person rounding the
    // printed number gets.
    //
    // Blast radius, measured rather than assumed: across every observation
    // in both artifacts, at the decimal count each route really renders,
    // this changes ZERO figures in `web/data-derived` (the artifact
    // production publishes) and 37 of 1031 in the synthetic test fixture —
    // all of them in the straight-line history that fixture's own
    // `source.txt` says was generated by a formula, which is why so many of
    // its values land exactly on a half and real INE readings do not.
    expect((70.865).toFixed(2)).toBe("70.86");
    expect(formatNumber(70.865, 2)).toBe("70,87");
    expect(formatNumber(-70.865, 2)).toBe("-70,87");
  });

  it("keeps same-magnitude values the same length, so a tabular-nums column stays aligned", () => {
    // PRD §12.1 puts every numeral in `tabular-nums`, which equalises DIGIT
    // advance widths. Grouping separators are not digits, so the guarantee
    // only survives if two values of the same magnitude receive the same
    // number of them — which is what makes right-aligned value columns line
    // up rather than ripple.
    const column = [49687120, 49612345, 22779123].map((v) => formatNumber(v, 0));
    expect(new Set(column.map((s) => s.length)).size).toBe(1);
  });
});

describe("formatSignedPercent — the header's year-on-year and intra-annual figures", () => {
  it("carries an explicit plus sign for a rise, so the direction is readable without comparison", () => {
    expect(formatSignedPercent(3.4, 1)).toBe("+3,4%");
  });

  it("uses the Spanish decimal comma for a fall too, and no doubled sign", () => {
    expect(formatSignedPercent(-2.15, 1)).toBe("-2,2%");
  });

  it("treats zero as non-negative, matching the sign rule the header already used", () => {
    expect(formatSignedPercent(0, 1)).toBe("+0,0%");
  });

  it("appends a bare percent sign with no space", () => {
    // Deliberately NOT `Intl`'s own `style: "percent"`: that multiplies the
    // value by 100 (these rates are already percentages) and inserts a
    // U+00A0 before the sign. The literal suffix keeps this change to the
    // one thing that was wrong — the decimal separator.
    expect(formatSignedPercent(12, 1)).toBe("+12,0%");
  });
});
