// The ONE place a number becomes reader-facing text on this site.
//
// WHY THIS MODULE EXISTS. Every numeral a reader saw was produced by
// `Number.prototype.toFixed`, in seven separate call sites: the homepage
// card, the indicator page header, its two variation figures, the
// accessible data table (twice — the static one and the island's), and the
// chart's generated textual description. `toFixed` is locale-blind by
// specification — it always emits a `.` decimal point and never a grouping
// separator — so a site served entirely as `lang="es"` published
// `49687120 personas` and `22779 miles de personas`. Seven call sites is
// also why this is a module and not a fix in the component that happened to
// be noticed: a numeric-formatting policy that lives in a component is a
// policy the next component does not inherit.
//
// THE MACHINE-READABLE BOUNDARY, STATED SO IT IS NOT CROSSED BY ACCIDENT.
// This module formats text a PERSON reads. It must never touch:
//
//   - `/data-derived/csv/*.csv` and `/data-derived/series/*.json`. Those are
//     written by the Go pipeline (`app/internal/publishing`), are covered by
//     manifest.json's sha256 digest chain, and are consumed by programs.
//     `1.234,5` in a CSV cell breaks every consumer and every digest. The web
//     tree never generates either file — `ActionBar` links to the published
//     bytes — so the boundary is structural here, not a rule someone has to
//     remember.
//   - SVG geometry. `svg.ts` and `geometry.ts` serialise coordinates with
//     `toFixed(2)` into `x`, `y`, `d` and `transform` attributes, which the
//     SVG grammar requires to use a `.` decimal point. A comma there is a
//     coordinate separator, so a "localised" path would silently redraw the
//     chart.
//   - Permalink query parameters and any other value round-tripped back
//     into code.
//
// WHY `Intl.NumberFormat` AND NOT A SEPARATOR LOOP. The Spanish rule is not
// "a dot every three digits": CLDR gives `es` a `minimumGroupingDigits` of
// 2, so a four-digit number is written `1234` and not `1.234` (RAE,
// *Ortografía* §11.5.1.2). A hand-rolled loop gets that wrong, and gets it
// wrong invisibly — no fixture series currently has a four-digit latest
// value, so no page test would notice.
//
// ONE BEHAVIOURAL DIFFERENCE, DISCLOSED RATHER THAN DISCOVERED LATER.
// `Intl` and `toFixed` do not agree on an exact decimal half.
// `(70.865).toFixed(2)` is "70.86" — it rounds the BINARY double, which is
// 70.86499999999999488… — while `Intl` rounds the decimal the artifact
// published and returns "70,87", the answer a person rounding the printed
// number gets. Measured across every observation in both artifacts, at the
// decimal count each route really renders: ZERO figures change in
// `web/data-derived` (the artifact production publishes) and 37 of 1031 in
// the synthetic test fixture, all in the straight-line history that
// fixture's own `source.txt` says was generated by a formula — which is why
// so many of its values sit exactly on a half and real INE readings do not.
// `test/format/number.test.ts` pins the behaviour.

/** The one locale this site publishes in. Hoisted to a constant so the
 * places that format text and the `<html lang="es">` the pages declare are
 * visibly the same decision rather than two independent ones.
 *
 * EXPORTED so `./date.ts` consumes this exact value instead of re-typing
 * `"es-ES"` beside it. Two literals in two files are two decisions that can
 * drift; one exported constant is the single decision this comment already
 * claimed it was. */
export const LOCALE = "es-ES";

/** `Intl.NumberFormat` construction is the expensive part, and these
 * formatters are re-created per observation when a 294-point series renders
 * its data table. Keyed by decimal count because that is the only axis they
 * vary on. */
const FORMATTERS = new Map<number, Intl.NumberFormat>();

function formatterFor(decimals: number): Intl.NumberFormat {
  const cached = FORMATTERS.get(decimals);
  if (cached) return cached;

  const formatter = new Intl.NumberFormat(LOCALE, {
    // Both bounds, not just the maximum: a series configured to four
    // decimals must render 121,9959 AND 22,0000, or a column of values
    // reports a precision that changes row by row.
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
    // "min2" is the Spanish rule spelled out rather than inherited: group
    // from five digits up, leave four alone. It is deliberately NOT
    // `useGrouping: true`, which the NumberFormat v3 specification maps to
    // "always" and which would render 1234 as "1.234"; and deliberately not
    // left to the default, so that a future CLDR revision to `es` cannot
    // change what this site prints without a code change.
    useGrouping: "min2",
  });
  FORMATTERS.set(decimals, formatter);
  return formatter;
}

/**
 * One observation value as a Spanish reader reads it: `22.779`,
 * `49.687.120`, `121,9959`.
 *
 * `decimals` is the series' own configured precision and is always honoured
 * exactly — rounded UP to and padded OUT to. PIB is configured to four on
 * purpose, and a formatter that normalised every series to two would erase
 * three published digits of `121,9959`.
 */
export function formatNumber(value: number, decimals: number): string {
  return formatterFor(decimals).format(value);
}

/**
 * A variation rate for the page header: `+3,4%`, `-2,2%`.
 *
 * The explicit `+` is carried over from the header this replaces, and is
 * the point of the function: a rate whose sign a reader has to infer from
 * its absence is a rate they read as a level.
 *
 * Deliberately NOT `Intl`'s own `style: "percent"`. That style multiplies
 * its input by 100 — these values are already percentages, so it would
 * publish `340%` for a 3.4% rise — and it inserts a U+00A0 before the sign,
 * changing spacing this change has no mandate to touch. Only the decimal
 * separator was wrong; only the decimal separator changes.
 */
export function formatSignedPercent(value: number, decimals = 1): string {
  const sign = value >= 0 ? "+" : "";
  return `${sign}${formatNumber(value, decimals)}%`;
}
